### ISSUE TITLE
Installation Not Verified

### ISSUE THREAD

**Issue by Nmora21** [acoular/spectacoular#20]
After installing Spectacoular using Anaconda, none of the pre built apps seem to be present in the installation so the MicGeomExample, Measurement_App, etc. could not be run.

**Comment by adku1173** [comment]
The apps are available in the directory: https://github.com/acoular/spectacoular/tree/master/apps . You can clone the repository via git, navigate to the apps directory and start one of the apps (as described here: https://acoular.github.io/spectacoular/apps/micgeomexample.html).
