### ISSUE TITLE
UMA16SamplesGenerator not found in project

### ISSUE THREAD

**Issue by dimakozin** [acoular/spectacoular#5]
Hi everyone!
I've just tried start **Measurement_App** with my **MiniDSP UMA16** mic array
Command from [this file](https://github.com/acoular/spectacoular/blob/eed39695df6c81cb179eae7429a020f71ed00dfc/apps/start_uma.sh#L2)
`bokeh serve --show Measurement_App --args --device=uma16 --blocksize=256`

**Log:**
`    from acuma16 import UMA16SamplesGenerator
ModuleNotFoundError: No module named 'acuma16'
`

I can't find any UMA16 modules in project
Any ideas?

**Comment by adku1173** [comment]
Hi @dimakozin, 
the problem has been fixed for the latest version of the master branch (07dd637).
According to the [documentation](https://acoular.github.io/spectacoular/apps/measurementapp.html), one can start the app by using the sounddevice library which provides access to audio streams available by the PortAudio library. Simply do
`bokeh serve --show Measurement_App --args --device=sounddevice --blocksize=256
`,
which will open the browser with the following content: 

![image](https://user-images.githubusercontent.com/28733219/192539784-2f0e6706-9e48-4d34-a281-fddae91638ef.png)
There you can select the nanoSHARC microphone array.

Thanks for reporting the issue!
